import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { toolingRoot } from './check-terms.ts';
import { rootTransitions } from '../skills/dispatch/scripts/machines/root.ts';
import { reviewTransitions } from '../skills/dispatch/scripts/machines/review.ts';
import { planTransitions } from '../skills/dispatch/scripts/machines/plan.ts';
import { transitions as designTransitions } from '../skills/dispatch/scripts/machines/design.ts';
import { implementTransitions } from '../skills/dispatch/scripts/machines/implement.ts';
export function diagram(): string {
  const machines = { root: rootTransitions, design: designTransitions, plan: planTransitions, review: reviewTransitions, implement: implementTransitions };
  return '# Dispatch maintainer notes\n\nGenerated by `node scripts/diagram.ts --root <root>` from declared transitions.\n' + Object.entries(machines).map(([name, transitions]) => `\n## ${name}\n\n\`\`\`mermaid\nstateDiagram-v2\n${[...new Set(transitions.map((t) => `  ${t.from} --> ${t.to}: ${t.on}`))].sort().join('\n')}\n\`\`\`\n`).join('');
}
export function writeDiagram(root: string): void { const dir = path.resolve(root, 'docs'); fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(path.join(dir, 'dispatch-notes.md'), diagram()); }
if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) { writeDiagram(toolingRoot(process.argv.slice(2))); }
