#!/usr/bin/env node

/**
 * @file copilot-run.mjs
 * @description Dedicated runner for GitHub Copilot.
 *
 * Supports cross-platform execution (macOS / Windows / Linux, bash / zsh / PowerShell).
 * Implements strict order of preference:
 *   1. Copilot VS Code Extension (`copilot vscode`)
 *   2. Standalone GitHub Copilot CLI (`copilot cli`)
 *
 * Reaches and tests each mode up to executable launch (e.g. `--version`) so
 * environments without active Copilot tokens or subscriptions can still verify
 * reachability and fallback cleanly across modes.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildAttachmentBlock,
  classifyFailure,
  createSessionLogger,
  createTraceWriter,
  DEFAULT_TIMEOUT_SECONDS,
  emitCompletionBanner,
  emitInitBanner,
  describeGitStatusDiff,
  extractCleanResponse,
  findBinary,
  formatSafetyPrompt,
  getGitStatus,
  getSanitizedEnv,
  parseCommonArgs,
  preparePromptForArgv,
  PROJECT_ROOT,
  readStdin,
  spawnCli,
  spawnCliSync,
  terminateProcessTree,
} from './common.mjs';

const currentFilePath = fileURLToPath(import.meta.url);

// ============================================================================
// SECTION: Cross-Platform Binary Discovery & Reachability
// ============================================================================

/**
 * Checks whether a given path points to an existing file that can be executed.
 *
 * @param {string} targetPath File path to inspect
 * @returns {boolean}
 */
export function isExecutableFile(targetPath) {
  if (!targetPath || typeof targetPath !== 'string') return false;
  try {
    const stat = fs.statSync(targetPath);
    if (!stat.isFile()) return false;

    // OS: POSIX (macOS & Linux) | Check executable bit
    if (process.platform !== 'win32') {
      try {
        fs.accessSync(targetPath, fs.constants.X_OK);
        return true;
      } catch {
        // Fallback for sandboxes or network shares where accessSync(X_OK) errs
        return (stat.mode & 0o111) !== 0;
      }
    }

    // OS: Windows (win32) | Regular file presence is sufficient
    return true;
  } catch {
    return false;
  }
}

/**
 * Gathers candidate executable paths for the VS Code Copilot Chat extension.
 *
 * Mode: Copilot VS Code Extension (`vscode`)
 * Supported OS: macOS, Windows, Linux
 *
 * @returns {string[]} Ordered array of candidate paths
 */
export function getCopilotVscodeCandidates() {
  const homeDir = os.homedir();
  const candidates = [];

  // --------------------------------------------------------------------------
  // BRANCH: macOS (darwin) | Mode: VS Code Extension
  // Probes globalStorage of VS Code, VS Code Insiders, VSCodium, and Cursor.
  // --------------------------------------------------------------------------
  if (process.platform === 'darwin') {
    const macEditors = [
      'Code',
      'Code - Insiders',
      'VSCodium',
      'Cursor',
    ];
    for (const editor of macEditors) {
      candidates.push(
        path.join(
          homeDir,
          'Library/Application Support',
          editor,
          'User/globalStorage/github.copilot-chat/copilotCli/copilot',
        ),
      );
    }
  }

  // --------------------------------------------------------------------------
  // BRANCH: Windows (win32) | Mode: VS Code Extension
  // Probes %APPDATA% and %LOCALAPPDATA% for VS Code, VS Code Insiders, and VSCodium.
  // Tests .bat, .cmd, .exe, .ps1, and extensionless launchers generated by the extension.
  // --------------------------------------------------------------------------
  if (process.platform === 'win32') {
    const appData = process.env.APPDATA || path.join(homeDir, 'AppData', 'Roaming');
    const localAppData = process.env.LOCALAPPDATA || path.join(homeDir, 'AppData', 'Local');
    const winBases = [appData, localAppData].filter(Boolean);
    const winEditors = ['Code', 'Code - Insiders', 'VSCodium'];
    const winLaunchers = ['copilot.bat', 'copilot.cmd', 'copilot.exe', 'copilot.ps1', 'copilot'];

    for (const base of winBases) {
      for (const editor of winEditors) {
        for (const launcher of winLaunchers) {
          candidates.push(
            path.join(
              base,
              editor,
              'User',
              'globalStorage',
              'github.copilot-chat',
              'copilotCli',
              launcher,
            ),
          );
        }
      }
    }
  }

  // --------------------------------------------------------------------------
  // BRANCH: Linux | Mode: VS Code Extension
  // Probes standard XDG config, Flatpak, and Snap locations for Code and variants.
  // --------------------------------------------------------------------------
  if (process.platform === 'linux') {
    const configDir = process.env.XDG_CONFIG_HOME || path.join(homeDir, '.config');
    const linuxEditors = ['Code', 'Code - Insiders', 'VSCodium'];

    // Standard native / package manager installations
    for (const editor of linuxEditors) {
      candidates.push(
        path.join(
          configDir,
          editor,
          'User/globalStorage/github.copilot-chat/copilotCli/copilot',
        ),
      );
    }

    // Flatpak installation paths
    candidates.push(
      path.join(
        homeDir,
        '.var/app/com.visualstudio.code/config/Code/User/globalStorage/github.copilot-chat/copilotCli/copilot',
      ),
    );

    // Snap installation paths (current and common revisions)
    candidates.push(
      path.join(
        homeDir,
        'snap/code/current/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/copilot',
      ),
    );
    candidates.push(
      path.join(
        homeDir,
        'snap/code/common/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/copilot',
      ),
    );
  }

  return candidates;
}

/**
 * Gathers candidate executable paths for standalone GitHub Copilot CLI.
 *
 * Mode: Standalone Copilot CLI (`cli`)
 * Supported OS: macOS, Windows, Linux
 *
 * @returns {string[]} Ordered array of candidate fallback paths
 */
export function getCopilotCliCandidates() {
  const homeDir = os.homedir();
  const candidates = [];

  // --------------------------------------------------------------------------
  // BRANCH: macOS (darwin) | Mode: Standalone Copilot CLI
  // Probes Homebrew (Apple Silicon & Intel), user local bin, and npm global prefixes.
  // --------------------------------------------------------------------------
  if (process.platform === 'darwin') {
    candidates.push(
      '/opt/homebrew/bin/copilot',
      '/usr/local/bin/copilot',
      path.join(homeDir, '.local/bin/copilot'),
      path.join(homeDir, '.npm-global/bin/copilot'),
    );
  }

  // --------------------------------------------------------------------------
  // BRANCH: Windows (win32) | Mode: Standalone Copilot CLI
  // Probes npm global binaries, %LOCALAPPDATA%\Programs, %ProgramFiles%, and user bin.
  // --------------------------------------------------------------------------
  if (process.platform === 'win32') {
    const appData = process.env.APPDATA || path.join(homeDir, 'AppData', 'Roaming');
    const localAppData = process.env.LOCALAPPDATA || path.join(homeDir, 'AppData', 'Local');
    const progFiles = process.env.ProgramFiles || 'C:\\Program Files';

    candidates.push(
      path.join(appData, 'npm', 'copilot.cmd'),
      path.join(appData, 'npm', 'copilot'),
      path.join(localAppData, 'npm', 'copilot.cmd'),
      path.join(localAppData, 'npm', 'copilot'),
      path.join(localAppData, 'Programs', 'copilot', 'copilot.exe'),
      path.join(progFiles, 'GitHub Copilot', 'copilot.exe'),
      path.join(homeDir, '.local', 'bin', 'copilot.cmd'),
      path.join(homeDir, '.local', 'bin', 'copilot.exe'),
    );
  }

  // --------------------------------------------------------------------------
  // BRANCH: Linux | Mode: Standalone Copilot CLI
  // Probes /usr/local/bin, /usr/bin, Linuxbrew, ~/.local/bin, and npm global prefixes.
  // --------------------------------------------------------------------------
  if (process.platform === 'linux') {
    candidates.push(
      '/usr/local/bin/copilot',
      '/usr/bin/copilot',
      '/home/linuxbrew/.linuxbrew/bin/copilot',
      path.join(homeDir, '.local/bin/copilot'),
      path.join(homeDir, '.npm-global/bin/copilot'),
    );
  }

  return candidates;
}

/**
 * Locates the VS Code Copilot Chat extension binary.
 *
 * Mode: Copilot VS Code Extension (`vscode`)
 * Cross-platform (macOS / Windows / Linux).
 *
 * @returns {string|null} Path to executable or null if not installed
 */
export function getCopilotVscodeBinary() {
  const candidates = getCopilotVscodeCandidates();
  for (const candidate of candidates) {
    if (isExecutableFile(candidate)) {
      return candidate;
    }
  }
  return null;
}

/**
 * Locates the standalone GitHub Copilot CLI executable.
 *
 * Mode: Standalone Copilot CLI (`cli`)
 * Cross-platform (macOS / Windows / Linux).
 * Probes system PATH first, then OS-specific candidate install locations.
 *
 * @returns {string|null} Path to executable or null if not installed
 */
export function getCopilotCliBinary() {
  const candidates = getCopilotCliCandidates();
  const binName = process.platform === 'win32' ? 'copilot.cmd' : 'copilot';
  return findBinary(binName, candidates);
}

/**
 * Tests whether a Copilot executable is reachable on the current system.
 *
 * Reachability Probe:
 * Runs `copilot --version` with a short timeout.
 * DOES NOT require an active GitHub Copilot subscription or valid OAuth token:
 * testing up to binary execution validates reachability for that mode without
 * failing due to credentials.
 *
 * @param {string} binary Path to Copilot executable
 * @returns {{ reachable: boolean, version: string|null, error: string|null }}
 */
export function testCopilotReachability(binary) {
  if (!binary || typeof binary !== 'string') {
    return { reachable: false, version: null, error: 'Binary path not specified' };
  }
  try {
    const res = spawnCliSync(binary, ['--version'], { encoding: 'utf8', timeout: 5000 });
    if (res.status === 0) {
      const firstLine = (res.stdout || res.stderr || '').trim().split(/\r?\n/)[0];
      return { reachable: true, version: firstLine, error: null };
    }
    return {
      reachable: false,
      version: null,
      error: `Process exited with code ${res.status}: ${(res.stderr || res.stdout || '').trim()}`,
    };
  } catch (err) {
    return { reachable: false, version: null, error: err.message };
  }
}

/**
 * Returns all viable Copilot targets in order of preference:
 *   1. Copilot VS Code Extension (`vscode`)
 *   2. Standalone Copilot CLI (`cli`)
 *
 * Each target is probed up to executable reachability.
 *
 * @param {'auto'|'vscode'|'cli'} [preferredMode='auto']
 * @returns {Array<{ mode: 'vscode'|'cli', name: string, binary: string, version: string|null }>}
 */
export function getViableCopilotTargets(preferredMode = 'auto') {
  const norm = String(preferredMode || 'auto').toLowerCase();
  const modes = [
    { mode: 'vscode', name: 'Copilot VS Code Extension', fn: getCopilotVscodeBinary },
    { mode: 'cli', name: 'Standalone Copilot CLI', fn: getCopilotCliBinary },
  ];

  const ordered =
    norm === 'vscode' || norm === 'cli' ? modes.filter((m) => m.mode === norm) : modes;

  const viable = [];
  for (const item of ordered) {
    const bin = item.fn();
    if (bin) {
      const probe = testCopilotReachability(bin);
      if (probe.reachable) {
        viable.push({ mode: item.mode, name: item.name, binary: bin, version: probe.version });
      }
    }
  }

  // If reachability probe was inconclusive (e.g. timeout in sandbox), fall back to checking on-disk binary
  if (viable.length === 0) {
    for (const item of ordered) {
      const bin = item.fn();
      if (bin) {
        viable.push({ mode: item.mode, name: item.name, binary: bin, version: null });
      }
    }
  }

  return viable;
}

/**
 * Resolves the active Copilot binary and execution mode.
 *
 * Order of Preference:
 *   1. Copilot VS Code Extension (`vscode`) - highest priority
 *   2. Standalone Copilot CLI (`cli`) - fallback
 *
 * @param {'auto'|'vscode'|'cli'} [preferredMode='auto'] Desired mode selection
 * @returns {{ binary: string, mode: 'vscode'|'cli', name: string } | null}
 */
export function resolveCopilotTarget(preferredMode = 'auto') {
  const viable = getViableCopilotTargets(preferredMode);
  if (viable.length > 0) {
    return viable[0];
  }
  return null;
}

/**
 * Returns the path to the preferred Copilot executable.
 *
 * Preserves preference: copilot vscode > copilot cli.
 *
 * @param {'auto'|'vscode'|'cli'} [preferredMode='auto']
 * @returns {string|null}
 */
export function getCopilotBinary(preferredMode = 'auto') {
  const target = resolveCopilotTarget(preferredMode);
  return target ? target.binary : null;
}

/**
 * Probes availability and reachability across both Copilot modes.
 *
 * Allows users and tests to inspect which modes are installed and reachable
 * without requiring subscriptions or active tokens.
 *
 * @returns {{
 *   vscode: { binary: string|null, reachable: boolean, version: string|null, error: string|null },
 *   cli: { binary: string|null, reachable: boolean, version: string|null, error: string|null },
 *   preferred: { mode: 'vscode'|'cli', binary: string, name: string } | null
 * }}
 */
export function probeCopilotModes() {
  const vscodeBin = getCopilotVscodeBinary();
  const cliBin = getCopilotCliBinary();

  const vscodeProbe = testCopilotReachability(vscodeBin);
  const cliProbe = testCopilotReachability(cliBin);

  const target = resolveCopilotTarget('auto');

  return {
    vscode: { binary: vscodeBin, ...vscodeProbe },
    cli: { binary: cliBin, ...cliProbe },
    preferred: target,
  };
}

/**
 * Checks if GitHub Copilot is installed and reachable.
 *
 * Tests reachability (via `--version`) up to the resolved mode.
 * Does not require an active subscription or token.
 *
 * @param {'auto'|'vscode'|'cli'} [preferredMode='auto']
 * @returns {Promise<boolean>}
 */
export async function isCopilotAvailable(preferredMode = 'auto') {
  const target = resolveCopilotTarget(preferredMode);
  if (!target || !target.binary) return false;
  return testCopilotReachability(target.binary).reachable;
}

/**
 * Extracts Copilot session ID from output text.
 *
 * @param {string} text Raw stdout or stderr
 * @returns {string|null}
 */
export function extractCopilotSessionId(text) {
  if (!text) return null;
  const match =
    text.match(/"session_id"\s*:\s*"([a-zA-Z0-9_-]+)"/) ||
    text.match(/session\s+id[:=]\s*([a-zA-Z0-9_-]{8,})/i) ||
    text.match(/copilot\s+--resume\s+([a-zA-Z0-9_-]{8,})/i);
  return match ? match[1] : null;
}

/**
 * Classifies Copilot-specific execution failures.
 *
 * Specifically catches credential, OAuth, and subscription errors when a mode
 * is reachable but not subscribed or lacks tokens.
 *
 * @param {string} text Raw stdout and stderr
 * @returns {'quota'|'context-overflow'|'auth'|'not-found'|'timeout'|null}
 */
export function classifyCopilotFailure(text) {
  if (!text || typeof text !== 'string') return null;

  // BRANCH: Authentication & Token Missing Signatures
  // e.g. "Error: No authentication information found."
  // "Copilot can be authenticated with GitHub using an OAuth Token..."
  // "You need an active GitHub Copilot subscription."
  if (
    /(no authentication|can be authenticated|oauth token|personal access token|gh auth login|subscription required|not subscribed|active github copilot subscription)/i.test(
      text,
    )
  ) {
    return 'auth';
  }

  return classifyFailure(text);
}

export const DEFAULT_COPILOT_MODEL = 'gpt-5.6-luna';
export const DEFAULT_COPILOT_EFFORT = 'max';

// ============================================================================
// SECTION: Execution Runner
// ============================================================================

/**
 * Runs a prompt through GitHub Copilot.
 *
 * Respects order of preference: copilot vscode > copilot cli.
 * Supports cross-platform execution (macOS / Windows / Linux).
 * If a mode is reachable but lacks subscription/tokens, cascades to the next
 * available mode when running in auto mode.
 *
 * @param {Object} [options]
 * @param {string} [options.prompt]
 * @param {string[]} [options.files]
 * @param {string} [options.model]
 * @param {string} [options.effort]
 * @param {number} [options.timeout]
 * @param {number} [options.maxBufferMb]
 * @param {boolean} [options.verbose]
 * @param {'auto'|'vscode'|'cli'} [options.copilotMode]
 * @returns {Promise<Object>}
 */
export async function runCopilot(options = {}) {
  const {
    prompt,
    files = [],
    model = DEFAULT_COPILOT_MODEL,
    effort = DEFAULT_COPILOT_EFFORT,
    timeout = DEFAULT_TIMEOUT_SECONDS,
    maxBufferMb = 10,
    verbose = false,
    copilotMode = 'auto',
  } = options;

  // Resolve viable targets following preference: copilot vscode > copilot cli
  const viableTargets = getViableCopilotTargets(copilotMode);

  if (viableTargets.length === 0) {
    const err = new Error(
      'GitHub Copilot was not found in VS Code extension storage or system PATH.\n' +
        'Preference order: Copilot VS Code extension > Standalone Copilot CLI.\n' +
        '- Mode [copilot vscode]: Install GitHub Copilot Chat extension in VS Code.\n' +
        '- Mode [copilot cli]: npm install -g @github/copilot (or brew install copilot)',
    );
    err.code = 'CLI_NOT_FOUND';
    err.failureKind = 'not-found';
    throw err;
  }

  const sessionLogger = createSessionLogger('copilot');
  const initialGitStatus = getGitStatus();

  const attachments = buildAttachmentBlock(files);
  for (const note of attachments.notes) {
    process.stderr.write(`[dispatch] Attachment ${note}\n`);
  }

  const fullPrompt = attachments.text ? `${attachments.text}\n\n${prompt}` : prompt;
  const formattedPrompt = formatSafetyPrompt(fullPrompt, {
    workspaceRoot: PROJECT_ROOT,
    attachedFiles: files,
  });

  const effectiveModel = model || DEFAULT_COPILOT_MODEL;
  const effectiveEffort = effort || DEFAULT_COPILOT_EFFORT;

  /** Executes prompt against a single resolved Copilot target */
  const executeOnTarget = async (target) => {
    const bin = target.binary;

    // Headless print mode (interactive mode removed — delegates are always headless)
    const { prompt: argvPrompt, briefFile } = preparePromptForArgv(formattedPrompt, 'copilot');
    const copilotArgs = ['-p', argvPrompt];

    if (effectiveModel) {
      copilotArgs.push('--model', effectiveModel);
    }

    if (effectiveEffort) {
      copilotArgs.push('--effort', effectiveEffort);
    }

    copilotArgs.push('--mode', 'plan');

    emitInitBanner({
      provider: `GitHub Copilot [${target.mode}] (${target.mode === 'vscode' ? 'copilot vscode' : 'copilot cli'})`,
      logFile: sessionLogger.logFile,
      mode: 'READ-ONLY',
    });

    const trace = createTraceWriter(verbose);

    return new Promise((resolve, reject) => {
      let stdoutBuffer = '';
      let stderrBuffer = '';
      let totalOutputBytes = 0;
      let isTimedOut = false;
      let isBufferExceeded = false;
      const maxBufferBytes = maxBufferMb * 1024 * 1024;

      const child = spawnCli(bin, copilotArgs, {
        cwd: PROJECT_ROOT,
        env: getSanitizedEnv(),
        stdio: ['ignore', 'pipe', 'pipe'],
        shell: false,
      });

      const timer = setTimeout(() => {
        isTimedOut = true;
        terminateProcessTree(child);
      }, timeout * 1000);

      const cleanup = () => {
        clearTimeout(timer);
        terminateProcessTree(child);
      };

      child.stdout.on('data', (chunk) => {
        totalOutputBytes += chunk.length;
        if (totalOutputBytes > maxBufferBytes) {
          if (!isBufferExceeded) {
            isBufferExceeded = true;
            terminateProcessTree(child);
          }
          return;
        }
        stdoutBuffer += chunk.toString('utf8');
        sessionLogger.write(chunk);
        if (trace) trace(chunk);
      });

      child.stderr.on('data', (chunk) => {
        stderrBuffer += chunk.toString('utf8');
        sessionLogger.write(chunk);
        if (trace) trace(chunk);
      });

      child.on('close', (code, signal) => {
        clearTimeout(timer);

        const sessionId =
          extractCopilotSessionId(stdoutBuffer) || extractCopilotSessionId(stderrBuffer);
        const sessionLink = sessionId ? `copilot --resume ${sessionId}` : null;

        let gitIntegrityViolation = false;
        let gitIntegrityDetails = null;
        if (initialGitStatus !== null) {
          const finalGitStatus = getGitStatus();
          if (finalGitStatus !== null && finalGitStatus !== initialGitStatus) {
            gitIntegrityViolation = true;
            gitIntegrityDetails = describeGitStatusDiff(initialGitStatus, finalGitStatus);
          }
        }

        // A truncated run still carries its partial analysis; return captured output
        const truncated = isTimedOut ? 'timeout' : isBufferExceeded ? 'buffer' : null;
        const exitCode = truncated ? (isTimedOut ? 124 : 137) : (code ?? (signal ? 1 : 0));
        const failureKind =
          classifyCopilotFailure(`${stderrBuffer}\n${stdoutBuffer}`) || truncated;

        emitCompletionBanner({
          provider: `GitHub Copilot [${target.mode}] (${target.mode === 'vscode' ? 'copilot vscode' : 'copilot cli'})`,
          sessionLink,
          exitCode,
          truncated,
        });

        resolve({
          provider: 'copilot',
          mode: target.mode,
          binary: bin,
          stdout: extractCleanResponse(stdoutBuffer),
          rawStdout: stdoutBuffer,
          stderr: stderrBuffer,
          exitCode,
          logFile: sessionLogger.logFile,
          briefFile,
          sessionId,
          sessionLink,
          truncated,
          failureKind,
          gitIntegrityViolation,
          gitIntegrityDetails,
        });
      });

      child.on('error', (err) => {
        cleanup();
        err.code = 1;
        err.stderr = stderrBuffer;
        err.failureKind = classifyCopilotFailure(`${stderrBuffer}\n${err.message}`);
        reject(err);
      });
    });
  };

  let lastResult = null;

  // Execute across viable targets with fallback on auth/quota failure
  for (let i = 0; i < viableTargets.length; i++) {
    const currentTarget = viableTargets[i];
    const isLastTarget = i === viableTargets.length - 1;

    try {
      const result = await executeOnTarget(currentTarget);
      const isQuotaOrAuth = result.failureKind === 'quota' || result.failureKind === 'auth';

      // If this mode is not subscribed or lacks tokens, cascade to next available mode
      if (isQuotaOrAuth && !isLastTarget && (!copilotMode || copilotMode === 'auto')) {
        process.stderr.write(
          `[dispatch] Notice: ${currentTarget.name} exited with '${result.failureKind}' (not subscribed or token missing).\n` +
            `[dispatch] Cascading to next available mode (${viableTargets[i + 1].name})...\n`,
        );
        lastResult = result;
        continue;
      }

      sessionLogger.close();
      return result;
    } catch (err) {
      if (!isLastTarget && (!copilotMode || copilotMode === 'auto')) {
        process.stderr.write(
          `[dispatch] Warning: ${currentTarget.name} execution failed (${err.message}). Cascading to next mode...\n`,
        );
        continue;
      }
      sessionLogger.close();
      throw err;
    }
  }

  sessionLogger.close();
  return lastResult;
}

// ============================================================================
// SECTION: CLI Entrypoint
// ============================================================================

/**
 * Parses Copilot-specific flags in addition to common dispatch arguments.
 */
function parseCopilotArgs(argv) {
  const options = parseCommonArgs(argv);
  options.copilotMode = 'auto';
  options.probeOnly = false;

  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--test' || arg === '--probe' || arg === '--check' || arg === '--test-modes') {
      options.probeOnly = true;
    } else if (arg === '--copilot-mode' && argv[i + 1]) {
      options.copilotMode = argv[++i];
    } else if (arg.startsWith('--copilot-mode=')) {
      options.copilotMode = arg.slice('--copilot-mode='.length);
    }
  }

  return options;
}

export async function main() {
  const options = parseCopilotArgs(process.argv);

  if (options.help) {
    console.log(`
GitHub Copilot Runner (copilot)

Order of Preference:
  1. Copilot VS Code Extension ('vscode')
  2. Standalone Copilot CLI ('cli')

Cross-Platform Support:
  - macOS: VS Code globalStorage probe, Homebrew, user binaries
  - Windows: %APPDATA% / %LOCALAPPDATA% globalStorage (.bat/.cmd/.exe/.ps1), npm global
  - Linux: XDG config (~/.config), Flatpak, Snap, /usr/local/bin, /usr/bin

Usage:
  node scripts/copilot-run.mjs [options] [prompt]

Options:
  -p, --prompt <string>         The prompt message to send
  -f, --file, --artifact        Attach context file or artifact (repeatable)
  -m, --model <name>            Override Copilot model (default: ${DEFAULT_COPILOT_MODEL})
  -e, --effort <level>          Override reasoning effort (default: ${DEFAULT_COPILOT_EFFORT})
  -t, --timeout <seconds>       Override timeout in seconds (default: ${DEFAULT_TIMEOUT_SECONDS})
  --copilot-mode <mode>         Explicit mode preference: 'vscode', 'cli', or 'auto' (default: auto)
  --test, --probe               Test reachability across modes without requiring tokens or prompt
  -v, --verbose                 Stream live trace to stderr (terminal only; ignored when piped)
  -h, --help                    Show this help
`);
    process.exit(0);
  }

  // --------------------------------------------------------------------------
  // BRANCH: Reachability Probe Mode (`--test` / `--probe`)
  // Validates execution up to --version without requiring token or subscription.
  // --------------------------------------------------------------------------
  if (options.probeOnly) {
    const probe = probeCopilotModes();
    console.log('[dispatch] GitHub Copilot Reachability Status:');
    console.log(
      `  - Mode [copilot vscode] (priority 1): ${
        probe.vscode.reachable
          ? `REACHABLE (${probe.vscode.binary}) [${probe.vscode.version}]`
          : probe.vscode.binary
          ? `FOUND BUT UNREACHABLE (${probe.vscode.binary}: ${probe.vscode.error})`
          : 'NOT FOUND'
      }`,
    );
    console.log(
      `  - Mode [copilot cli]    (priority 2): ${
        probe.cli.reachable
          ? `REACHABLE (${probe.cli.binary}) [${probe.cli.version}]`
          : probe.cli.binary
          ? `FOUND BUT UNREACHABLE (${probe.cli.binary}: ${probe.cli.error})`
          : 'NOT FOUND'
      }`,
    );

    if (probe.preferred) {
      console.log(
        `\n  -> Selected Target: mode=${probe.preferred.mode}, binary=${probe.preferred.binary}`,
      );
      console.log(
        '  -> Verification: Reached successfully via executable invocation. Active subscription/token not required for reachability test.',
      );
      process.exit(0);
    } else {
      console.error('\n  -> Error: Neither VS Code Copilot extension nor Standalone Copilot CLI is reachable.');
      process.exit(1);
    }
  }

  const pipedStdin = await readStdin();
  let finalPrompt = options.prompt.trim();
  if (pipedStdin) {
    finalPrompt = finalPrompt
      ? `${finalPrompt}\n\n[Piped Input]:\n${pipedStdin}`
      : pipedStdin;
  }

  if (!finalPrompt) {
    console.error('Error: No prompt provided. Use --test to probe reachability or -p to pass a prompt.');
    process.exit(1);
  }

  try {
    const res = await runCopilot({ ...options, prompt: finalPrompt });
    if (res.stdout) {
      process.stdout.write(res.stdout.endsWith('\n') ? res.stdout : `${res.stdout}\n`);
    } else if (res.failureKind === 'auth') {
      console.error(
        `\n[dispatch] Copilot was reached via mode '${res.mode}', but lacks authentication/subscription credentials.\n` +
          `Session log: ${res.logFile}`,
      );
    }
    if (res.gitIntegrityViolation) {
      console.warn(`\n[dispatch] WARNING: Workspace was modified during READ-ONLY execution!`);
      if (res.gitIntegrityDetails) {
        console.warn(`[dispatch] Changed files:\n${res.gitIntegrityDetails}`);
      }
      console.warn('');
    }
    process.exit(res.stdout ? res.exitCode : (res.failureKind ? 1 : res.exitCode));
  } catch (err) {
    console.error(`\n[dispatch] ERROR: ${err.message}`);
    process.exit(typeof err.code === 'number' ? err.code : 1);
  }
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(currentFilePath)
) {
  main().catch((err) => {
    console.error(`Fatal error: ${err.message}`);
    process.exit(1);
  });
}
