import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { toolingRoot } from './check-terms.ts';
import type { Transition } from '../skills/dispatch/scripts/core/types.ts';
import { rootTransitions } from '../skills/dispatch/scripts/machines/root.ts';
import { reviewTransitions } from '../skills/dispatch/scripts/machines/review.ts';
import { planTransitions } from '../skills/dispatch/scripts/machines/plan.ts';
import { transitions as designTransitions } from '../skills/dispatch/scripts/machines/design.ts';
import { implementTransitions } from '../skills/dispatch/scripts/machines/implement.ts';
function machineDiagram(transitions: readonly Transition[]): string {
  const states = [...new Set(transitions.flatMap(({ from, to }) => [from, to]))].sort();
  const ids = new Map(states.map((state, index) => [state, `S${index}`]));
  const idFor = (state: string): string => {
    const id = ids.get(state);
    if (id === undefined) throw new Error(`Missing Mermaid id for state "${state}".`);
    return id;
  };
  // Mermaid ids stay simple while declarations retain the machine's state names.
  const declarations = states.map((state) => `  state "${state}" as ${idFor(state)}`).join('\n');
  const edges = [...new Set(transitions.map((transition) => `  ${idFor(transition.from)} --> ${idFor(transition.to)}: ${transition.on}`))].sort().join('\n');
  return `${declarations}\n${edges}`;
}
export function diagram(): string {
  const machines = { root: rootTransitions, design: designTransitions, plan: planTransitions, review: reviewTransitions, implement: implementTransitions };
  return '# Dispatch state diagrams\n\nGenerated by `node scripts/diagram.ts --root <root>` from declared transitions.\n' + Object.entries(machines).map(([name, transitions]) => `\n## ${name}\n\n\`\`\`mermaid\nstateDiagram-v2\n${machineDiagram(transitions)}\n\`\`\`\n`).join('');
}
export function writeDiagram(root: string): void { const dir = path.resolve(root, 'docs'); fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(path.join(dir, 'state-diagrams.md'), diagram()); }
export function checkDiagram(root: string): boolean {
  const file = path.resolve(root, 'docs/state-diagrams.md');
  return fs.existsSync(file) && fs.readFileSync(file, 'utf8') === diagram();
}
if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const args = process.argv.slice(2), root = toolingRoot(args);
  if (args.includes('--check')) {
    if (!checkDiagram(root)) {
      process.stderr.write('docs/state-diagrams.md is out of date; run `npm run diagrams` from the repository root to regenerate it.\n');
      process.exitCode = 1;
    }
  } else writeDiagram(root);
}
