import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  extractActionHeadingRecords,
  extractApprovedPathSet,
  structuralLines,
} from '../../../skills/dispatch/scripts/plan-structure.mjs';

describe('shared plan structure parser', () => {
  it('retains valid, duplicate, conflicting, and invalid action headings with stable loci', () => {
    const source = [
      '## Proposed Changes',
      '#### [NEW] `src/a.js`',
      '#### [NEW] ./src/a.js — duplicate',
      '#### [DELETE] src/a.js',
      '#### [MODIFY] ../escape.js',
      '#### [NEW] src\\\\windows.js',
      '#### [NEW] `src/file with spaces.js` — note',
      '#### [NEW] `src/arbitrary.js` (generated by build)',
    ].join('\n');

    assert.deepEqual(extractActionHeadingRecords(source), [
      { action: 'NEW', rawPath: 'src/a.js', path: 'src/a.js', rejectionReason: null, line: 2 },
      { action: 'NEW', rawPath: './src/a.js', path: 'src/a.js', rejectionReason: null, line: 3 },
      { action: 'DELETE', rawPath: 'src/a.js', path: 'src/a.js', rejectionReason: null, line: 4 },
      { action: 'MODIFY', rawPath: '../escape.js', path: null, rejectionReason: 'parent-segment', line: 5 },
      { action: 'NEW', rawPath: 'src\\\\windows.js', path: null, rejectionReason: 'backslash', line: 6 },
      { action: 'NEW', rawPath: 'src/file with spaces.js', path: 'src/file with spaces.js', rejectionReason: null, line: 7 },
      { action: 'NEW', rawPath: 'src/arbitrary.js', path: 'src/arbitrary.js', rejectionReason: null, line: 8 },
    ]);
    assert.deepEqual(extractApprovedPathSet(source), ['src/a.js', 'src/arbitrary.js', 'src/file with spaces.js']);
  });

  it('recognizes headings only beneath the unique Proposed Changes owner', () => {
    const source = [
      '#### [NEW] before.js',
      '## Proposed Changes',
      '### Group',
      '#### [MODIFY] inside.js',
      '##### [NEW] wrong-depth.js',
      '## Verification Plan',
      '#### [NEW] after.js',
    ].join('\n');
    assert.deepEqual(extractActionHeadingRecords(source).map(({ path }) => path), ['inside.js']);
  });

  it('removes fenced code, comments, and quotes while preserving inline code', () => {
    const source = [
      '## Proposed Changes',
      '> #### [NEW] quoted.js',
      '<!-- #### [NEW] hidden.js -->',
      '```md',
      '#### [NEW] fenced.js',
      '```',
      'Text `#### [NEW] inline.js`',
      '#### [NEW] visible.js <!-- annotation -->',
    ].join('\n');
    const lines = structuralLines(source);
    assert.equal(lines.length, 8);
    assert.equal(lines[6].text, 'Text `#### [NEW] inline.js`');
    assert.deepEqual(extractActionHeadingRecords(source).map(({ path }) => path), ['visible.js']);
  });
});
